version: '3'
services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
                - ./app:/app
        ports:
            - "9000:9000"
        command: sh -c "jupyter lab --ip=0.0.0.0 --port 9000 --allow-root --notebook-dir=/app"
        stdin_open: true
        restart: always